// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CarCenter.Domain.Models
{
    public partial class Carros
    {
        public int CarroId { get; set; }
        public string Marca { get; set; }
        public int? Modelo { get; set; }
        public string Placa { get; set; }
        public string Observaciones { get; set; }
        public int? ClienteId { get; set; }

        public virtual Clientes Cliente { get; set; }
    }
}