// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CarCenter.Domain.Models
{
    public partial class Clientes
    {
        public Clientes()
        {
            Carros = new HashSet<Carros>();
            Facturas = new HashSet<Facturas>();
        }

        public int ClienteId { get; set; }
        public string TipoCliente { get; set; }
        public int? PersonaId { get; set; }

        public virtual Personas Persona { get; set; }
        public virtual ICollection<Carros> Carros { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}