// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CarCenter.Domain.Models
{
    public partial class Mecanicos
    {
        public int MecanicoId { get; set; }
        public bool Estado { get; set; }
        public int? PersonaId { get; set; }

        public virtual Personas Persona { get; set; }
    }
}