// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CarCenter.Domain.Models
{
    public partial class Personas
    {
        public Personas()
        {
            Clientes = new HashSet<Clientes>();
            Mecanicos = new HashSet<Mecanicos>();
        }

        public int PersonaId { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string Celular { get; set; }
        public string CorreoElectronico { get; set; }

        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Mecanicos> Mecanicos { get; set; }
    }
}