// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CarCenter.Domain.Models
{
    public partial class Productos
    {
        public Productos()
        {
            DetalleFacturas = new HashSet<DetalleFacturas>();
        }

        public int ProductoId { get; set; }
        public string Nombre { get; set; }
        public decimal? ValorUnitario { get; set; }
        public int? VecesVendido { get; set; }

        public virtual ICollection<DetalleFacturas> DetalleFacturas { get; set; }
    }
}