// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CarCenter.Domain.Models
{
    public partial class Sedes
    {
        public Sedes()
        {
            Facturas = new HashSet<Facturas>();
        }

        public int SedeId { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}